WIP: title fallback using contract name and tokenID
ourzora/nft-components pull request #109
Opened 2021-12-02 23:08 UTC by dblodorn

@iainnash this would be a nice feature so we "always" have a title available for the Token.
I did notice that when using betaIndexer the contract title & symbol are not available, so perhaps we include this in  nft-hooks query, or simply surface the contract name and symbol in the nft object.

<img width="613" alt="Screen Shot 2021-12-02 at 3 06 43 PM" src="https://user-images.githubusercontent.com/7268786/144517341-3897e253-cd39-4012-b3e2-035488947fd9.png">

![Screen Shot 2021-12-02 at 2 55 24 PM](https://user-images.githubusercontent.com/7268786/144517414-0455f3fe-6e21-4ab9-9a00-1d01ad363575.png)

![Screen Shot 2021-12-02 at 2 55 17 PM](https://user-images.githubusercontent.com/7268786/144517425-0c507694-b9d6-4a87-bc16-f595ee6bb465.png)

2021-12-18 01:09 UTC, dblodorn commented
@iainnash FWIW - this is an interesting metadata contrast between betaIndexer and external data source:

![Screen Shot 2021-12-17 at 4 38 23 PM](https://user-images.githubusercontent.com/7268786/146623872-214bed7b-45e8-4a99-9bda-27acfc453a36.png)

![Screen Shot 2021-12-17 at 4 27 35 PM](https://user-images.githubusercontent.com/7268786/146623875-2ed0ffe3-33f0-4faa-8fbd-1ae148a0206f.png)

2021-12-20 13:32 UTC, iainnash requested changes

2021-12-20 13:32 UTC, iainnash commented on src/nft-full/CollectionTag.tsx
> +  console.log(data)
nit rm console.log

2021-12-20 13:32 UTC, iainnash commented on src/nft-full/CollectionTag.tsx
> +          {data && "openseaInfo" in data && data.openseaInfo.asset_contract.image_url !== null
there should be data.nft.contract.image now from opensea

2021-12-20 13:32 UTC, iainnash commented on src/nft-full/MediaInfo.tsx
> +      console.log(metadata)
nit console.log

2022-04-29 12:38 UTC, iainnash commented
This is stale, will close for now.

2022-04-29 12:38 UTC, closed without merging